skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
oracle_consumer = "GujZcMQix2ctpPHstodSJMDbmdw6zcPmhFEpQJAWFvUX"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
